Repository social-protocols/jabble, pull requests merged in 2024-05, with the labels that each got.

#46 Fix nReplies in getScoredPostInternal
  app/ranking.ts
Labels: ready-to-merge-squash

#45 Lint with Earthfile
  .github/workflows/deploy.yml
  Earthfile
  flake.nix
Labels: ready-to-merge-squash

#48 deploy with earthly
  .github/workflows/deploy.yml
  Earthfile
  data.db
Labels: ready-to-merge-squash

#53 Remove note attachment
  app/components/ui/post.tsx
Labels: ready-to-merge-squash

#57 envrc: add warning when env vars from .env.example are missing
  .envrc
Labels: ready-to-merge-squash

#51 Show critical thread and add indicators for needed votes, update remix to 2.9.2, update critical thread data model, remove note attachment
  README.md
  app/components/ui/feed.tsx
  app/components/ui/post.tsx
  app/components/ui/reply-thread.tsx
  app/conversations.ts
  app/db/kysely-types.ts
  app/db/types.ts
  app/positions.ts
  app/ranking.ts
  app/routes/tags+/$tag.posts.$postId.tsx
  app/routes/tags+/$tag.stats.$postId.tsx
  app/routes/tags+/$tag_.tsx
  app/routes/vote.tsx
  app/vote.ts
  migrations/2024-05-07-critical-id.ts
  package-lock.json
  package.json
  remix.config.js
Labels: ready-to-merge-squash

#58 Remove some unused code and an unnecessary route
  app/components/floating-toolbar.tsx
  app/routes/settings+/profile.index.tsx
  app/routes/users+/index.tsx
Labels: ready-to-merge-squash

#52 Don't show notes on tag page
  app/routes/tags+/$tag_.tsx
Labels: ready-to-merge-squash

#59 Update README.md
  README.md
Labels: ready-to-merge-squash

#61 Replace deprecated DataFunctionArgs with LoaderFunctionArgs and ActionFunctionArgs
  app/entry.server.tsx
  app/post.ts
  app/root.tsx
  app/routes/_auth+/dev-login.tsx
  app/routes/_auth+/forgot-password.tsx
  app/routes/_auth+/login.tsx
  app/routes/_auth+/logout.tsx
  app/routes/_auth+/onboarding.tsx
  app/routes/_auth+/reset-password.tsx
  app/routes/_auth+/signup.tsx
  app/routes/_auth+/verify.tsx
  app/routes/_seo+/robots[.]txt.ts
  app/routes/_seo+/sitemap[.]xml.ts
  app/routes/index.tsx
  app/routes/me.tsx
  app/routes/resources+/healthcheck.tsx
  app/routes/settings+/profile.change-email.tsx
  app/routes/settings+/profile.index.tsx
  app/routes/settings+/profile.password.tsx
  app/routes/settings+/profile.password_.create.tsx
  app/routes/settings+/profile.tsx
  app/routes/settings+/profile.two-factor.disable.tsx
  app/routes/settings+/profile.two-factor.index.tsx
  app/routes/settings+/profile.two-factor.verify.tsx
  app/routes/tags+/$tag.posts.$postId.tsx
  app/routes/tags+/$tag.stats.$postId.tsx
  app/routes/tags+/$tag_.tsx
  app/routes/users+/$username.tsx
  app/schema.ts
  app/score-events.ts
Labels: ready-to-merge-squash

#56 eslint: forbid exclamation marks
  .eslintrc.cjs
  app/components/ui/Truncate.tsx
  app/components/ui/feed.tsx
  app/conversations.ts
  app/post.ts
  app/ranking.ts
  app/root.tsx
  app/routes/_auth+/dev-login.tsx
  app/routes/_auth+/forgot-password.tsx
  app/routes/settings+/profile.change-email.tsx
  app/routes/settings+/profile.index.tsx
  app/routes/settings+/profile.password.tsx
  app/routes/settings+/profile.password_.create.tsx
  app/routes/settings+/profile.two-factor.disable.tsx
  app/routes/settings+/profile.two-factor.index.tsx
  app/routes/settings+/profile.two-factor.verify.tsx
  app/score-events.ts
  app/tag.ts
  app/vote-events.ts
  app/vote.ts
Labels: ready-to-merge-squash

#63 Display convincingness on notes
  app/components/ui/post.tsx
  app/components/ui/reply-thread.tsx
  app/conversations.ts
Labels: ready-to-merge-squash

#43 Integrate globalbrain-node node extension for calling GlobalBrain.jl from javascript
  .github/workflows/deploy.yml
  .gitignore
  .npmrc
  Dockerfile
  Earthfile
  app/globalbrain.ts
  app/post.ts
  app/routes/reply.tsx
  app/routes/vote.tsx
  app/score-events.ts
  app/utils/env.server.ts
  app/vote-events.ts
  app/vote.ts
  ci_sh.sh
  flake.lock
  flake.nix
  justfile
  package-lock.json
  package.json
  remix.config.js
  server/index.ts
  startup.sh
  tests/globalbrain-node.js
Labels: ready-to-merge-squash

#65 earthly 0.8.10 for all jobs
  .github/workflows/deploy.yml
Labels: ready-to-merge-squash

#66 install fuse3 in flake fdietze 2024 05 17
  Earthfile
  flake.nix
Labels: ready-to-merge-squash

#67 install busybox for swap tooling, base nix shell
  Earthfile
  flake.nix
  justfile
  other/litefs.yml
Labels: ready-to-merge-squash

#69 Delete data.db
  data.db
Labels: ready-to-merge-squash

#68 Add post deletion functionality
  app/components/ui/deleted-post.tsx
  app/components/ui/post.tsx
  app/components/ui/reply-thread.tsx
  app/db/kysely-types.ts
  app/post.ts
  app/ranking.ts
  app/root.tsx
  app/routes/deletePost.tsx
  app/routes/index.tsx
  app/routes/restorePost.tsx
  app/routes/tags+/$tag.posts.$postId.tsx
  app/utils/auth.server.ts
  import-hn.ts
  migrations/2024-05-17-make-posts-deletable.ts
  seed.ts
Labels: ready-to-merge-squash

#72 Replay vote events
  other/replay-vote-events.ts
  other/replay.sh
Labels: ready-to-merge-squash

#73 fix: blue dot by reloading
  app/components/ui/post.tsx
  app/routes/tags+/$tag.posts.$postId.tsx
Labels: ready-to-merge-squash

#77 Use latest GlobalBrain.jl
  Earthfile
Labels: ready-to-merge-rebase

#78 Run database operations in transactions
  app/conversations.ts
  app/globalbrain.ts
  app/post.ts
  app/ranking.ts
  app/routes/deletePost.tsx
  app/routes/index.tsx
  app/routes/reply.tsx
  app/routes/restorePost.tsx
  app/routes/tags+/$tag.posts.$postId.tsx
  app/routes/tags+/$tag.stats.$postId.tsx
  app/routes/tags+/$tag_.tsx
  app/routes/vote.tsx
  app/tag.ts
  app/vote.ts
  import-hn.ts
  other/import-society-library-debatemap.ts
  other/replay-vote-events.ts
  seed.ts
Labels: bug, ready-to-merge-squash

#80 Bug direct replies
  app/ranking.ts
Labels: ready-to-merge-squash

#83 use globalbrain artifact from GlobalBrain.jl repo
  Earthfile
  flake.nix
  justfile
Labels: ready-to-merge-squash

#88 just 'recent sessions' to get recent sessions from prod DB
  justfile
  other/recent-sessions.sh
Labels: ready-to-merge-rebase

#64 Playwright E2E smoke test
  .github/workflows/test.yml
  .gitignore
  Earthfile
  docker-compose.yml
  e2e/example.spec.ts
  flake.nix
  playwright.config.ts
Labels: ready-to-merge-squash

#91 just docker-run uses docker-compose (ctrl+c works now)
  justfile
Labels: ready-to-merge-squash

#93 remove aws-sdk dependency
  package-lock.json
  package.json
Labels: ready-to-merge-squash

#79 Fix tag page state bug
  app/routes/tags+/$tag_.tsx
Labels: ready-to-merge-rebase
